### ISSUE TITLE
Integration doesn't work

### ISSUE THREAD

**Issue by prodigy7** [mattermost/mattermost-plugin-jitsi#169]
**Mattermost Version**
v5.24.1

**Plugin Version**
v2.0.0

**Describe the issue**
Integration with jitsi doesn't work. So far all parameters are configured but when I call /jitsi, i got only the message "Received invalid response from server". Same time I see the following stacktrace.

**Server Error Logs**
```
app_1  | goroutine 2791 [running]:
app_1  | runtime/debug.Stack(0x0, 0x0, 0x1280980)
app_1  |        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
app_1  | runtime/debug.PrintStack()
app_1  |        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
app_1  | github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x16ffd20, 0xc421343e80, 0x16fd440, 0x2070a70, 0x1, 0xc421754f40, 0x1, 0x1)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:89 +0x70
app_1  | github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x1709300, 0xc421cffea0, 0x16ffd20, 0xc421343e80, 0x16fd440, 0x2070a70, 0x1)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:74 +0xe5
app_1  | panic(0x1333ee0, 0x20141c0)
app_1  |        /usr/local/go/src/runtime/panic.go:502 +0x229
app_1  | github.com/mattermost/mattermost-server/app.(*App).HandleCommandResponse(0xc4200de580, 0xc4215dd2c0, 0xc4221f78c0, 0x0, 0x1, 0xc42221d400, 0x0)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/command.go:277 +0x10d
app_1  | github.com/mattermost/mattermost-server/app.(*App).ExecuteCommand(0xc4200de580, 0xc4221f78c0, 0x0, 0x0)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/command.go:171 +0x2205
app_1  | github.com/mattermost/mattermost-server/api4.executeCommand(0xc4229d1c00, 0x1709300, 0xc421cffea0, 0xc4229d1b00)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/api4/command.go:227 +0x35f
app_1  | github.com/mattermost/mattermost-server/web.Handler.ServeHTTP(0xc4200de580, 0x15aba38, 0x10001, 0x1709300, 0xc421cffea0, 0xc4229d1b00)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/web/handlers.go:131 +0x126d
app_1  | github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202c40e0, 0x1709300, 0xc421cffea0, 0xc4229d1b00)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162 +0xed
app_1  | github.com/mattermost/mattermost-server/app.(*RateLimiter).RateLimitHandler.func1(0x1709300, 0xc421cffea0, 0xc4229d1900)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/ratelimit.go:107 +0xca
app_1  | net/http.HandlerFunc.ServeHTTP(0xc421343e80, 0x1709300, 0xc421cffea0, 0xc4229d1900)
app_1  |        /usr/local/go/src/net/http/server.go:1947 +0x44
app_1  | github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x16ffd20, 0xc421343e80, 0x16fd440, 0x2070a70, 0x1, 0x1709300, 0xc421cffea0, 0xc4229d1900)
app_1  |        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78 +0xb9
app_1  | net/http.serverHandler.ServeHTTP(0xc421d8c5b0, 0x1709300, 0xc421cffea0, 0xc4229d1900)
app_1  |        /usr/local/go/src/net/http/server.go:2694 +0xbc
app_1  | net/http.(*conn).serve(0xc422a9c460, 0x170a400, 0xc422c23380)
app_1  |        /usr/local/go/src/net/http/server.go:1830 +0x651
app_1  | created by net/http.(*Server).Serve
app_1  |        /usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Additional context**
Jitsi is configured for authentication with ldap. It also runs inside a docker container (maybe any additional port/api is neccessary?)

**Comment by hanzei** [comment]
@prodigy7 Can you reproduce the issue with a newer version of Mattermost?
